Orchard CMS/Modules/Orchard.DynamicForms/Controllers/SubmissionAdminController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Orchard.DynamicForms.Helpers;
using Orchard.DynamicForms.Services;
using Orchard.DynamicForms.ViewModels;
using Orchard.Localization;
using Orchard.Mvc;
using Orchard.UI.Admin;
using Orchard.UI.Navigation;
using Orchard.UI.Notify;

namespace Orchard.DynamicForms.Controllers {
    [Admin]
    public class SubmissionAdminController : Controller {
        private readonly IFormService _formService;
        private readonly IOrchardServices _services;

        public SubmissionAdminController(IFormService formService, IOrchardServices services) {
            _formService = formService;
            _services = services;
            T = NullLocalizer.Instance;
        }

        public Localizer T { get; set; }

        public ActionResult Index(string id, PagerParameters pagerParameters) {
            var pager = new Pager(_services.WorkContext.CurrentSite, pagerParameters);
            var submissions = _formService.GetSubmissions(id, pager.GetStartIndex(), pager.PageSize);
            var pagerShape = _services.New.Pager(pager).TotalItemCount(submissions.TotalItemCount);
            var viewModel = new SubmissionsIndexViewModel {
                FormName = id,
                Submissions = _formService.GenerateDataTable(submissions),
                Pager = pagerShape
            };
            return View(viewModel);
        }

        public ActionResult Details(int id) {
            var submission = _formService.GetSubmission(id);

            if (submission == null)
                return HttpNotFound();

            var viewModel = new SubmissionViewModel {
                Submission = submission,
                NameValues = submission.ToNameValues()
            };
            return View(viewModel);
        }

        public ActionResult Delete(int id) {
            var submission = _formService.GetSubmission(id);

            if (submission == null)
                return HttpNotFound();

            _formService.DeleteSubmission(submission);
            _services.Notifier.Information(T("That submission has been deleted."));
            return Redirect(Request.UrlReferrer.ToString());
        }

        [FormValueRequired("submit.BulkEdit")]
        [ActionName("Index")]
        public ActionResult BulkDelete(IEnumerable<int> submissionIds) {
            if (submissionIds == null || !submissionIds.Any()) {
                _services.Notifier.Error(T("Please select the submissions to delete."));

            }
            else {
                var numDeletedSubmissions = _formService.DeleteSubmissions(submissionIds);
                _services.Notifier.Information(T("{0} submissions have been deleted.", numDeletedSubmissions));
            }

            return Redirect(Request.UrlReferrer.ToString());
        }
    }
}

Orchard CMS/Modules/Orchard.DynamicForms/Views/SubmissionAdmin/Details.cshtml
@model Orchard.DynamicForms.ViewModels.SubmissionViewModel
@{
    Style.Require("DynamicForms.FormElements");
    Script.Require("ShapesBase");
}
@{
    Layout.Title = T("Submission for {0}", Model.Submission.FormName);
}
<table class="items">
    <thead>
        <tr>
            <th>@T("Field")</th>
            <th>@T("Value")</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>@T("ID")</td>
            <td>@Model.Submission.Id</td>
        </tr>
        <tr>
            <td>@T("Created")</td>
            <td>@Display.DateTime(DateTimeUtc: Model.Submission.CreatedUtc)</td>
        </tr>
        @foreach (string key in Model.NameValues) {
            <tr>
                <td>@key</td>
                <td>@Model.NameValues[key]</td>
            </tr>
        }
    </tbody>
</table>

Orchard CMS/Modules/Orchard.DynamicForms/Views/SubmissionAdmin/Index.cshtml
@using System.Data
@using Orchard.Utility.Extensions
@model Orchard.DynamicForms.ViewModels.SubmissionsIndexViewModel
@{
    Style.Include("forms-admin.css", "forms-admin.min.css"); // TODO: Shouldn't this be a Style.Require()?
    Script.Require("ShapesBase");
    Layout.Title = T("Submissions for {0}", Model.FormName);
}
@{
    var dataColumns = new List<DataColumn>();
    var dataColumnCount = Model.Submissions.Columns.Count > 11 ? 11 : Model.Submissions.Columns.Count;

    for (var i = 0; i < dataColumnCount; i++) {
        dataColumns.Add(Model.Submissions.Columns[i]);
    }
}
@using (Html.BeginFormAntiForgeryPost()) {
    <fieldset class="bulk-actions">
        <label for="publishActions">@T("Actions:")</label>
        <select id="publishActions" name="Options.BulkAction">
            @Html.SelectOption("", false, T("Choose action...").ToString())
            @Html.SelectOption("Delete", false, T("Delete").ToString())
        </select>
        <button type="submit" name="submit.BulkEdit" value="yes">@T("Apply")</button>
    </fieldset>
    <table class="items dynamic-forms-submissions">
        <thead>
            <tr>
                <th><input type="checkbox" class="check-all" /></th>
                @foreach (var dataColumn in dataColumns) {
                    <th>@dataColumn.ToString().CamelFriendly()</th>
                }
                <th></th>
            </tr>
        </thead>
        <tbody class="submissions">
            @foreach (DataRow dataRow in Model.Submissions.Rows) {
                var id = dataRow["Id"];
                <tr>
                    <td><input type="checkbox" value="@id" name="submissionIds" /></td>
                    @foreach (var dataColumn in dataColumns) {
                        <td>@dataRow[dataColumn]</td>
                    }
                    <td>
                        @Html.ActionLink(T("Details").Text, "Details", "SubmissionAdmin", new { id = id, area = "Orchard.DynamicForms" }, null) @T(" | ")
                        @Html.ActionLink(T("Remove").Text, "Delete", "SubmissionAdmin", new { id = id, area = "Orchard.DynamicForms" }, new { itemprop = "RemoveUrl UnsafeUrl" })
                    </td>
                </tr>
            }
        </tbody>
    </table>
    @Display(Model.Pager)
}